<!-- Primeira parte -->
<div id="main" class="center">
	<h1><span style="color: black"> <strong>- OLÁ AMIGOS!-</strong></span></h1>
</div>

<!-- Segunda parte -->
<div id="ola">
	<div class="container">

		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pharetra sed justo ut aliquet. Nulla hendrerit, nunc quis posuere bibendum, tortor elit facilisis arcu, eu sollicitudin tellus mauris eu turpis. Phasellus a libero cursus, feugiat elit quis, fringilla mi. Cras facilisis facilisis diam gravida ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor feugiat enim. Morbi luctus nibh libero, ut bibendum mauris lacinia nec. Curabitur id vulputate massa, at bibendum sem. Ut molestie dignissim libero convallis rhoncus. Morbi tincidunt massa nec ipsum ultricies, in sodales est placerat. Donec nec egestas libero. Aenean et eleifend odio. Nunc egestas fringilla felis, eu cursus urna consequat sit amet. Nullam at pulvinar tellus. Pellentesque euismod nunc ut tempus mollis.

			Curabitur pellentesque sed augue sed pretium. Vivamus viverra dui lectus, ac sodales arcu pretium eget. Pellentesque sit amet vulputate nunc, vitae pulvinar urna. Mauris quis nisi magna. In hac habitasse platea dictumst. Cras quis purus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris congue vestibulum neque, id accumsan velit facilisis id.

			Nulla ligula purus, varius in quam ut, mattis consequat justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel elit felis. Fusce ultrices eros eget ex volutpat faucibus. Ut sagittis dolor ut dolor posuere suscipit. Maecenas mollis, libero a elementum blandit, mauris arcu laoreet velit, quis tempor enim orci nec dolor. Praesent a neque quis tortor pulvinar aliquam non sed lorem. Vestibulum maximus, nisl viverra volutpat tempor, metus dolor varius turpis, eget semper dui ex eu justo. Phasellus efficitur purus ac massa molestie, a pretium mauris maximus. Nunc tempus tortor at gravida lacinia. Nunc mattis nulla sed convallis varius. Quisque lacinia erat mauris, et tempus quam gravida id. Integer cursus, quam non laoreet finibus, est quam imperdiet magna, quis ornare nisl eros sed sem. Quisque nec leo ipsum.

			Donec auctor, felis eu elementum pharetra, ex urna convallis magna, quis viverra metus sapien at lorem. Ut pellentesque, turpis in facilisis pulvinar, lectus turpis euismod ipsum, quis commodo tortor ex quis quam. Curabitur a aliquet sem, non tempor augue. Ut imperdiet magna quis nisi vulputate, id fringilla ipsum sagittis. Aliquam semper elit porta neque dictum ornare. Proin aliquet purus sed dui congue posuere. Vivamus libero arcu, aliquam sed mauris eget, ornare vestibulum ex. Donec aliquam mollis fringilla. Fusce commodo tortor quis condimentum vehicula. Praesent molestie lobortis tempus. Aliquam euismod tortor in finibus sagittis. Suspendisse ac enim at mauris pellentesque euismod. Sed efficitur justo sed dolor ultrices, ut feugiat leo ullamcorper. Donec vitae aliquet nunc. Maecenas nec urna eleifend, aliquam nulla ut, semper risus.

			Proin sed fringilla dolor. Phasellus fermentum pretium dapibus. Nunc eget felis ut leo ultricies sollicitudin non a nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ultrices ultricies ultrices. Praesent facilisis convallis nisi, et lacinia ex tincidunt a. Donec quis tristique augue. Pellentesque a lectus aliquet ligula ultricies placerat.

			Nulla mi leo, ullamcorper a varius vel, luctus eu eros. Aenean laoreet lacus eget cursus lobortis. Nam nulla ex, cursus sit amet lacus non, pretium rhoncus ante. Etiam interdum vulputate posuere. Integer pulvinar laoreet lorem, vel efficitur quam tempor a. Sed erat erat, dictum et sagittis eu, tempor a leo. Fusce maximus lectus quis volutpat mattis. Cras viverra suscipit varius. Morbi purus neque, bibendum id urna finibus, posuere dignissim orci.</p>
	

			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pharetra sed justo ut aliquet. Nulla hendrerit, nunc quis posuere bibendum, tortor elit facilisis arcu, eu sollicitudin tellus mauris eu turpis. Phasellus a libero cursus, feugiat elit quis, fringilla mi. Cras facilisis facilisis diam gravida ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor feugiat enim. Morbi luctus nibh libero, ut bibendum mauris lacinia nec. Curabitur id vulputate massa, at bibendum sem. Ut molestie dignissim libero convallis rhoncus. Morbi tincidunt massa nec ipsum ultricies, in sodales est placerat. Donec nec egestas libero. Aenean et eleifend odio. Nunc egestas fringilla felis, eu cursus urna consequat sit amet. Nullam at pulvinar tellus. Pellentesque euismod nunc ut tempus mollis.

			Curabitur pellentesque sed augue sed pretium. Vivamus viverra dui lectus, ac sodales arcu pretium eget. Pellentesque sit amet vulputate nunc, vitae pulvinar urna. Mauris quis nisi magna. In hac habitasse platea dictumst. Cras quis purus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris congue vestibulum neque, id accumsan velit facilisis id.

			Nulla ligula purus, varius in quam ut, mattis consequat justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel elit felis. Fusce ultrices eros eget ex volutpat faucibus. Ut sagittis dolor ut dolor posuere suscipit. Maecenas mollis, libero a elementum blandit, mauris arcu laoreet velit, quis tempor enim orci nec dolor. Praesent a neque quis tortor pulvinar aliquam non sed lorem. Vestibulum maximus, nisl viverra volutpat tempor, metus dolor varius turpis, eget semper dui ex eu justo. Phasellus efficitur purus ac massa molestie, a pretium mauris maximus. Nunc tempus tortor at gravida lacinia. Nunc mattis nulla sed convallis varius. Quisque lacinia erat mauris, et tempus quam gravida id. Integer cursus, quam non laoreet finibus, est quam imperdiet magna, quis ornare nisl eros sed sem. Quisque nec leo ipsum.

			Donec auctor, felis eu elementum pharetra, ex urna convallis magna, quis viverra metus sapien at lorem. Ut pellentesque, turpis in facilisis pulvinar, lectus turpis euismod ipsum, quis commodo tortor ex quis quam. Curabitur a aliquet sem, non tempor augue. Ut imperdiet magna quis nisi vulputate, id fringilla ipsum sagittis. Aliquam semper elit porta neque dictum ornare. Proin aliquet purus sed dui congue posuere. Vivamus libero arcu, aliquam sed mauris eget, ornare vestibulum ex. Donec aliquam mollis fringilla. Fusce commodo tortor quis condimentum vehicula. Praesent molestie lobortis tempus. Aliquam euismod tortor in finibus sagittis. Suspendisse ac enim at mauris pellentesque euismod. Sed efficitur justo sed dolor ultrices, ut feugiat leo ullamcorper. Donec vitae aliquet nunc. Maecenas nec urna eleifend, aliquam nulla ut, semper risus.

			Proin sed fringilla dolor. Phasellus fermentum pretium dapibus. Nunc eget felis ut leo ultricies sollicitudin non a nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ultrices ultricies ultrices. Praesent facilisis convallis nisi, et lacinia ex tincidunt a. Donec quis tristique augue. Pellentesque a lectus aliquet ligula ultricies placerat.

			Nulla mi leo, ullamcorper a varius vel, luctus eu eros. Aenean laoreet lacus eget cursus lobortis. Nam nulla ex, cursus sit amet lacus non, pretium rhoncus ante. Etiam interdum vulputate posuere. Integer pulvinar laoreet lorem, vel efficitur quam tempor a. Sed erat erat, dictum et sagittis eu, tempor a leo. Fusce maximus lectus quis volutpat mattis. Cras viverra suscipit varius. Morbi purus neque, bibendum id urna finibus, posuere dignissim orci.</p>
		
	</div>
</div>